name: cd

on:
  workflow_dispatch:
  push:
    tags: [ 'v-*' ]

permissions:
  id-token: write
  contents: read

jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Ref: https://github.com/osawa-koki/oidc-integration-github-aws
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v4
        with:
          path: ./node_modules/
          key: node-modules-${{ hashFiles('./**/package-lock.json') }}
      - name: Create dotenv file
        run: echo '${{ secrets.DOTENV }}' > ./.env
      - name: Install dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive
      - name: Install CDK
        run: npm install --global aws-cdk
      - name: Bootstrap
        run: cdk bootstrap
      - name: Synth
        run: cdk synth
      - name: Deploy
        run: cdk deploy --require-approval never --all
